import pandas as pd
from openpyxl import load_workbook
from openpyxl.utils import get_column_letter

# Create a list of dictionaries with 200 famous painters and their query strings.
data = [
    {"Artist": "Leonardo da Vinci", "Query String": "da vinci"},
    {"Artist": "Michelangelo Buonarroti", "Query String": "michelangelo"},
    {"Artist": "Raphael Sanzio", "Query String": "raphael"},
    {"Artist": "Rembrandt van Rijn", "Query String": "rembrandt"},
    {"Artist": "Pablo Picasso", "Query String": "picasso"},
    {"Artist": "Vincent van Gogh", "Query String": "van gogh"},
    {"Artist": "Claude Monet", "Query String": "monet"},
    {"Artist": "Titian", "Query String": "titian"},
    {"Artist": "Diego Velázquez", "Query String": "velazquez"},
    {"Artist": "Caravaggio (Michelangelo Merisi)", "Query String": "caravaggio"},
    {"Artist": "Johannes Vermeer", "Query String": "vermeer"},
    {"Artist": "Sandro Botticelli", "Query String": "botticelli"},
    {"Artist": "Jan van Eyck", "Query String": "van eyck"},
    {"Artist": "Albrecht Dürer", "Query String": "durer"},
    {"Artist": "Peter Paul Rubens", "Query String": "rubens"},
    {"Artist": "Paul Cézanne", "Query String": "cezanne"},
    {"Artist": "Édouard Manet", "Query String": "manet"},
    {"Artist": "Edgar Degas", "Query String": "degas"},
    {"Artist": "Pierre‑Auguste Renoir", "Query String": "renoir"},
    {"Artist": "Paul Gauguin", "Query String": "gauguin"},
    {"Artist": "Henri de Toulouse‑Lautrec", "Query String": "toulouse lautrec"},
    {"Artist": "Georges Seurat", "Query String": "seurat"},
    {"Artist": "Gustave Courbet", "Query String": "courbet"},
    {"Artist": "Édouard Vuillard", "Query String": "vuillard"},
    {"Artist": "Jackson Pollock", "Query String": "pollock"},
    {"Artist": "Mark Rothko", "Query String": "rothko"},
    {"Artist": "Andy Warhol", "Query String": "warhol"},
    {"Artist": "Roy Lichtenstein", "Query String": "lichtenstein"},
    {"Artist": "Willem de Kooning", "Query String": "kooning"},
    {"Artist": "Jasper Johns", "Query String": "johns"},
    {"Artist": "Robert Rauschenberg", "Query String": "rauschenberg"},
    {"Artist": "Paul Klee", "Query String": "klee"},
    {"Artist": "Wassily Kandinsky", "Query String": "kandinsky"},
    {"Artist": "Piet Mondrian", "Query String": "mondrian"},
    {"Artist": "Kazimir Malevich", "Query String": "malevich"},
    {"Artist": "Marc Chagall", "Query String": "chagall"},
    {"Artist": "Georges Braque", "Query String": "braque"},
    {"Artist": "Henri Matisse", "Query String": "matisse"},
    {"Artist": "André Derain", "Query String": "derain"},
    {"Artist": "Fernand Léger", "Query String": "leger"},
    {"Artist": "Juan Gris", "Query String": "gris"},
    {"Artist": "Amedeo Modigliani", "Query String": "modigliani"},
    {"Artist": "Giorgio de Chirico", "Query String": "de chirico"},
    {"Artist": "Man Ray", "Query String": "man ray"},
    {"Artist": "Alexander Calder", "Query String": "calder"},
    {"Artist": "Chuck Close", "Query String": "close"},
    {"Artist": "Cindy Sherman", "Query String": "sherman"},
    {"Artist": "Keith Haring", "Query String": "haring"},
    {"Artist": "Jean‑Michel Basquiat", "Query String": "basquiat"},
    {"Artist": "Frida Kahlo", "Query String": "kahlo"},
    {"Artist": "Diego Rivera", "Query String": "rivera"},
    {"Artist": "David Alfaro Siqueiros", "Query String": "siqueiros"},
    {"Artist": "José Clemente Orozco", "Query String": "orozco"},
    {"Artist": "Edward Hopper", "Query String": "hopper"},
    {"Artist": "J. M. W. Turner", "Query String": "turner"},
    {"Artist": "John Constable", "Query String": "constable"},
    {"Artist": "Winslow Homer", "Query String": "homer"},
    {"Artist": "Andrew Wyeth", "Query String": "wyeth"},
    {"Artist": "John Singer Sargent", "Query String": "sargent"},
    {"Artist": "Joshua Reynolds", "Query String": "reynolds"},
    {"Artist": "Thomas Gainsborough", "Query String": "gainsborough"},
    {"Artist": "Caspar David Friedrich", "Query String": "friedrich"},
    {"Artist": "Eugène Delacroix", "Query String": "delacroix"},
    {"Artist": "Jean‑Honoré Fragonard", "Query String": "fragonard"},
    {"Artist": "Jean‑Baptiste Greuze", "Query String": "greuze"},
    {"Artist": "Élisabeth Vigée Le Brun", "Query String": "vigée le brun"},
    {"Artist": "François Boucher", "Query String": "boucher"},
    {"Artist": "Jacques‑Louis David", "Query String": "david"},
    {"Artist": "Jean‑Marc Nattier", "Query String": "nattier"},
    {"Artist": "John Singleton Copley", "Query String": "copley"},
    {"Artist": "Thomas Eakins", "Query String": "eakins"},
    {"Artist": "Romare Bearden", "Query String": "bearden"},
    {"Artist": "Jacob Lawrence", "Query String": "lawrence"},
    {"Artist": "Mark Tobey", "Query String": "tobey"},
    {"Artist": "Barnett Newman", "Query String": "newman"},
    {"Artist": "Clyfford Still", "Query String": "still"},
    {"Artist": "Franz Kline", "Query String": "kline"},
    {"Artist": "Robert Motherwell", "Query String": "motherwell"},
    {"Artist": "Lee Krasner", "Query String": "krasner"},
    {"Artist": "Lucian Freud", "Query String": "freud"},
    {"Artist": "Francis Bacon", "Query String": "bacon"},
    {"Artist": "Gerhard Richter", "Query String": "richter"},
    {"Artist": "Anselm Kiefer", "Query String": "kiefer"},
    {"Artist": "Cy Twombly", "Query String": "twombly"},
    {"Artist": "Richard Diebenkorn", "Query String": "diebenkorn"},
    {"Artist": "Grant Wood", "Query String": "wood"},
    {"Artist": "Paul Delvaux", "Query String": "delvaux"},
    {"Artist": "René Magritte", "Query String": "magritte"},
    {"Artist": "Yves Tanguy", "Query String": "tanguy"},
    {"Artist": "Max Ernst", "Query String": "ernst"},
    {"Artist": "Salvador Dalí", "Query String": "dali"},
    {"Artist": "John Currin", "Query String": "currin"},
    {"Artist": "Joan Mitchell", "Query String": "mitchell"},
    {"Artist": "Egon Schiele", "Query String": "schiele"},
    {"Artist": "Oskar Schlemmer", "Query String": "schlemmer"},
    {"Artist": "Claude Bonnard", "Query String": "bonnard"},
    {"Artist": "Pierre Bonnard", "Query String": "bonnard"},
    {"Artist": "Georges Rouault", "Query String": "rouault"},
    {"Artist": "Suzanne Valadon", "Query String": "valadon"},
    {"Artist": "Odilon Redon", "Query String": "redon"},
    {"Artist": "Bridget Riley", "Query String": "riley"},
    {"Artist": "Victor Vasarely", "Query String": "vasarely"},
    {"Artist": "Julian Schnabel", "Query String": "schnabel"},
    {"Artist": "Richard Hamilton", "Query String": "hamilton"},
    {"Artist": "Philip Guston", "Query String": "guston"},
    {"Artist": "Eduardo Paolozzi", "Query String": "paolozzi"},
    {"Artist": "David Salle", "Query String": "salle"},
    {"Artist": "Richard Prince", "Query String": "prince"},
    {"Artist": "Jenny Saville", "Query String": "saville"},
    {"Artist": "Luc Tuymans", "Query String": "tuymans"},
    {"Artist": "Elizabeth Murray", "Query String": "murray"},
    {"Artist": "Julie Mehretu", "Query String": "mehretu"},
    {"Artist": "Kehinde Wiley", "Query String": "wiley"},
    {"Artist": "Kara Walker", "Query String": "walker"},
    {"Artist": "Kerry James Marshall", "Query String": "marshall"},
    {"Artist": "Mark Bradford", "Query String": "bradford"},
    {"Artist": "Njideka Akunyili Crosby", "Query String": "akunyili crosby"},
    {"Artist": "Takashi Murakami", "Query String": "murakami"},
    {"Artist": "Yoshitomo Nara", "Query String": "nara"},
    {"Artist": "Yinka Shonibare", "Query String": "shonibare"},
    {"Artist": "Marlene Dumas", "Query String": "dumas"},
    {"Artist": "Chris Ofili", "Query String": "ofili"},
    {"Artist": "Francis Alys", "Query String": "allys"},
    {"Artist": "El Anatsui", "Query String": "anatsui"},
    {"Artist": "Wifredo Lam", "Query String": "lam"},
    {"Artist": "Amrita Sher‑Gil", "Query String": "amrita sher gil"},
    {"Artist": "M. F. Husain", "Query String": "husain"},
    {"Artist": "Tyeb Mehta", "Query String": "mehta"},
    {"Artist": "F. N. Souza", "Query String": "souza"},
    {"Artist": "Sadequain", "Query String": "sadequain"},
    {"Artist": "Shahzia Sikander", "Query String": "sikander"},
    {"Artist": "Bhupen Khakhar", "Query String": "khakhar"},
    {"Artist": "Yayoi Kusama", "Query String": "kusama"},
    {"Artist": "Cecily Brown", "Query String": "brown"},
    {"Artist": "Sean Scully", "Query String": "scully"},
    {"Artist": "Elizabeth Peyton", "Query String": "peyton"},
    {"Artist": "Julian Opie", "Query String": "opie"},
    {"Artist": "Qi Baishi", "Query String": "qi baishi"},
    {"Artist": "Zhang Daqian", "Query String": "zhang daqian"},
    {"Artist": "Xu Beihong", "Query String": "xu beihong"},
    {"Artist": "Wu Guanzhong", "Query String": "wu guanzhong"},
    {"Artist": "Fan Kuan", "Query String": "fan kuan"},
    {"Artist": "Guo Xi", "Query String": "guo xi"},
    {"Artist": "Shen Zhou", "Query String": "shen zhou"},
    {"Artist": "Dong Qichang", "Query String": "dong qichang"},
    {"Artist": "Huang Binhong", "Query String": "huang binhong"},
    {"Artist": "Giuseppe Arcimboldo", "Query String": "arcimboldo"},
    {"Artist": "Bernardino Luini", "Query String": "luini"},
    {"Artist": "El Greco (Domenikos Theotokopoulos)", "Query String": "el greco"},
    {"Artist": "Giorgione", "Query String": "giorgione"},
    {"Artist": "Piero della Francesca", "Query String": "della francesca"},
    {"Artist": "Masaccio", "Query String": "masaccio"},
    {"Artist": "Fra Angelico", "Query String": "fra angelico"},
    {"Artist": "Andrea Mantegna", "Query String": "mantegna"},
    {"Artist": "Raja Ravi Varma", "Query String": "raja ravi varma"},
    {"Artist": "S. H. Raza", "Query String": "raza"},
    {"Artist": "Jamini Roy", "Query String": "roy"},
    {"Artist": "Nandalal Bose", "Query String": "bose"},
    {"Artist": "Katsushika Hokusai", "Query String": "hokusai"},
    {"Artist": "Utagawa Hiroshige", "Query String": "hiroshige"},
    {"Artist": "Kitagawa Utamaro", "Query String": "utamaro"},
    {"Artist": "Ablade Glover", "Query String": "glover"},
    {"Artist": "Ben Enwonwu", "Query String": "enwonwu"},
    {"Artist": "Rufino Tamayo", "Query String": "tamayo"},
    {"Artist": "Fernando Botero", "Query String": "botero"},
    {"Artist": "Zhang Xiaogang", "Query String": "zhang xiaogang"},
    {"Artist": "Liu Wei", "Query String": "liu wei"},
    {"Artist": "Zeng Fanzhi", "Query String": "zeng fanzhi"},
    {"Artist": "Cai Guo‑Qiang", "Query String": "cai guo qiang"},
    {"Artist": "Giovanni Bellini", "Query String": "bellini"},
    {"Artist": "Giorgio Vasari", "Query String": "vasari"},
    {"Artist": "Carlo Crivelli", "Query String": "crivelli"},
    {"Artist": "Bartolomé Esteban Murillo", "Query String": "murillo"},
    {"Artist": "Joaquín Sorolla", "Query String": "sorolla"},
    {"Artist": "Joaquín Torres García", "Query String": "torres garcia"},
    {"Artist": "David Hockney", "Query String": "hockney"},
    {"Artist": "Tracey Emin", "Query String": "emin"},
    {"Artist": "Sarah Lucas", "Query String": "lucas"},
    {"Artist": "Banksy", "Query String": "banksy"},
    {"Artist": "George Stubbs", "Query String": "stubbs"},
    {"Artist": "William Blake", "Query String": "blake"},
    {"Artist": "John William Waterhouse", "Query String": "waterhouse"},
    {"Artist": "Frederic Leighton", "Query String": "leighton"},
    {"Artist": "Paul Signac", "Query String": "signac"},
    {"Artist": "Gustave Moreau", "Query String": "moreau"},
    {"Artist": "Camille Pissarro", "Query String": "pissarro"},
    {"Artist": "Berthe Morisot", "Query String": "morisot"},
    {"Artist": "Mary Cassatt", "Query String": "cassatt"},
    {"Artist": "Artemisia Gentileschi", "Query String": "gentileschi"},
    {"Artist": "Sofonisba Anguissola", "Query String": "anguissola"},
    {"Artist": "Franz Marc", "Query String": "marc"},
    {"Artist": "Max Beckmann", "Query String": "beckmann"},
    {"Artist": "Emil Nolde", "Query String": "nolde"},
    {"Artist": "Giorgio Morandi", "Query String": "morandi"},
    {"Artist": "Alberto Giacometti", "Query String": "giacometti"},
    {"Artist": "Lyonel Feininger", "Query String": "feininger"},
    {"Artist": "Balthus", "Query String": "balthus"},
    {"Artist": "Francesco Guardi", "Query String": "guardi"},
    {"Artist": "Canaletto", "Query String": "canaletto"},
    {"Artist": "Giovanni Battista Tiepolo", "Query String": "tiepolo"},
]

# Create a DataFrame from the list.
df = pd.DataFrame(data)

# Save the DataFrame to an Excel file using ExcelWriter.
output_filename = "painters.xlsx"
with pd.ExcelWriter(output_filename, engine="openpyxl") as writer:
    df.to_excel(writer, index=False, sheet_name="Painters")

# Open the workbook to adjust column widths.
wb = load_workbook(output_filename)
ws = wb.active

# Adjust each column's width based on the maximum length of its contents.
for col in ws.columns:
    col_letter = get_column_letter(col[0].column)
    max_length = 0
    for cell in col:
        try:
            cell_length = len(str(cell.value))
            if cell_length > max_length:
                max_length = cell_length
        except:
            pass
    adjusted_width = max_length + 2  # add a little extra padding
    ws.column_dimensions[col_letter].width = adjusted_width

wb.save(output_filename)

print(f"Excel file '{output_filename}' has been created.")
